name: build
on:
  push:
    branches: [master, ovirt-engine-4.5*]
  pull_request:
    branches: [master, ovirt-engine-4.5*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream
            pip-command: pip3
          - name: centos-stream-10
            container-name: el10stream
            pip-command: pip3

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Install required PyPI packages
      run: ${{ matrix.pip-command }} install ansible-lint pylint mock paramiko psycopg2-binary websockify websocket-client looseversion isort pycodestyle pyflakes

    - name: Ensure required packages are available for linting
      run: dnf -y install otopi python3-ovirt-setup-lib python3-daemon

    - name: Checkout sources
      uses: ovirt/checkout-action@main

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Run python check
      run: build/python-check.sh

    - name: Create DNF repository
      run: |
        createrepo_c $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.ARTIFACTS_DIR }}
